import React from 'react';

const page = () => {
  return (
    <div className="p-4 max-w-7xl mx-auto">
       <h1 className='text-3xl font-bold'>Sobre nós</h1>
       <p className='my-6 animaLeft'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
       <p className='my-6 animaRight'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
       <p className='my-6 animaLeft'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
       <p className='my-6 animaRight'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
       <p className='my-6 animaLeft'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
       <p className='my-6 animaRight'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus neque, est ea praesentium atque quam incidunt maxime tenetur quibusdam esse cumque amet nemo reiciendis molestias voluptates rem alias corrupti porro ipsa debitis veritatis dicta quasi a eos! Pariatur, itaque eligendi exercitationem iusto possimus quod quo. Optio reprehenderit itaque error facere dolore, autem, obcaecati suscipit nesciunt doloribus mollitia consectetur nam culpa eaque, sint ipsa possimus? Ipsa veniam, iste officiis sint necessitatibus asperiores minus praesentium accusamus nam assumenda? Tempore perferendis veniam provident ut ea accusamus laboriosam dignissimos assumenda molestiae, magnam debitis accusantium possimus non doloribus voluptates necessitatibus sequi ipsa aliquam minima deserunt!</p>
    </div>
  );
};

export default page;